---
- name: Configure the home server
  hosts: raspberrypi
  remote_user: pi
  become: true

  tasks:
    - name: Install exfat driver package
      ansible.builtin.package:
        name: exfat-fuse
        state: present
    - name: Install Btrfs programs
      ansible.builtin.package:
        name: btrfs-progs
        state: present
    - name: Install borg backup
      ansible.builtin.package:
        name: borgbackup
        state: present
    - name: Mount external drivers by UUID
      ansible.posix.mount:
        path: /srv/shares/piratecove/meeseeks
        src: PARTUUID=51cd4731-719b-fe4f-8f8d-290b0dc86e9a
        fstype: btrfs
        state: mounted

  roles:
    - role: bertvv.samba
    - role: geerlingguy.pip
    - role: home-assistant-ansible
    - role: nephelaiio.unifi_controller

  vars:
    # These are needed for pip to work, because Debian still uses Python 2
    # https://github.com/geerlingguy/ansible-role-pip/issues/25#issuecomment-600343157
    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

    # nephelaiio.unifi_controller on Raspberry Pi
    unifi_java_packages: openjdk-8-jre-headless
    unifi_java_home: /usr/lib/jvm/java-8-openjdk-armhf/jre

    # bertvv.samba defaults
    samba_users:
      - name: pi
        password: insecure
    samba_shares:
      - name: piratecove
        comment: 'A place for pirates to hang out'
        write_list: pi
        public: yes
