---
- name: Configure the home server
  hosts: raspberrypi
  remote_user: pi
  become: true
  roles:
    - role: home-assistant.home-assistant-ansible
    - role: nephelaiio.unifi_controller
    - role: bertvv.samba
  vars:
    # nephelaiio.unifi_controller
    unifi_java_packages: openjdk-8-jre-headless
    unifi_java_home: /usr/lib/jvm/java-8-openjdk-armhf/jre
    # bertvv.samba
    samba_users:
    - name: pi
      password: insecure
    samba_shares:
    - name: piratecove
      comment: 'A place for pirates to hang out'
      write_list: pi
      public: yes
